//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выдача
    {
        public int ID { get; set; }
        public Nullable<int> Код_техники { get; set; }
        public Nullable<int> Код_сотр { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public bool Эксплуатация { get; set; }
        public string Статус { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Техника Техника { get; set; }
    }
}
