//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Выдача = new HashSet<Выдача>();
        }
    
        public int Код_сотр { get; set; }
        public string ФИО_сотр { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<int> Номер_кабинета { get; set; }
        public Nullable<int> Код_подразделения { get; set; }
        public Nullable<int> Код_должности { get; set; }
        public string Номер_телефона { get; set; }
        public string Статус_сотрудника { get; set; }
        public Nullable<System.DateTime> Дата_увольнения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдача> Выдача { get; set; }
        public virtual Должность Должность { get; set; }
        public virtual Кабинет Кабинет { get; set; }
        public virtual Подразделение Подразделение { get; set; }
    }
}
