//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Списание
    {
        public int Код { get; set; }
        public string ФИО_сотр { get; set; }
        public string Техника { get; set; }
        public Nullable<System.DateTime> Дата_списания { get; set; }
        public string Причина { get; set; }
    }
}
