//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Техника
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Техника()
        {
            this.Выдача = new HashSet<Выдача>();
        }
    
        public int Код { get; set; }
        public string Название { get; set; }
        public string Модель { get; set; }
        public string Параметры { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<System.DateTime> Дата_последнего_обновления { get; set; }
        public string Инвентарный_номер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдача> Выдача { get; set; }
    }
}
